# Generated by Django 3.0 on 2024-12-29 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='evstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicerequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=25)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Workwrservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
                ('serviceamount', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Workerpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment', models.BigIntegerField()),
                ('SERVICEREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Servicerequest')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock', models.FloatField()),
                ('fuel', models.CharField(max_length=400)),
                ('FUELSTATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FuelStation')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('FUELSTATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FuelStation')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('slotno', models.CharField(max_length=100)),
                ('EVSTATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evstation')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='SERVICE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Workwrservice'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=500)),
                ('rating', models.CharField(default='', max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Fuelrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Fuel', models.CharField(max_length=50)),
                ('FuelStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FuelStation')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Fuelpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment', models.BigIntegerField()),
                ('STOCK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Stock')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='evstation',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='evrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('BOOKING', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Booking')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
                ('evstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evstation')),
            ],
        ),
        migrations.CreateModel(
            name='evpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('payment', models.BigIntegerField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Booking')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=400)),
                ('reply', models.CharField(max_length=400)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chargingstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=60)),
                ('longtitude', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('EVSTATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evstation')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SLOT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Slot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('FUELREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuelrequest')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff')),
            ],
        ),
    ]
