# Generated by Django 3.0 on 2025-01-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrequest',
            name='Fuel',
        ),
        migrations.RemoveField(
            model_name='fuelrequest',
            name='FuelStation',
        ),
        migrations.AddField(
            model_name='fuelrequest',
            name='STOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Stock'),
            preserve_default=False,
        ),
    ]
