# Generated by Django 3.0 on 2025-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250112_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequest',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
