
from django.urls import path
from .import views


urlpatterns = [
    path('login/',views.login),
    path('login_post/',views.login_post),
    path('Admin_home/',views.home_admin),
    path('Admin_password_change/',views.password_change),
    path('password_post/',views.password_post),
    path('Admin_view_fuel/',views.view_fuel),
    path('Admin_view_fuel_post/',views.view_fuel_post),
    path('Admin_approve_fuel/',views.approve_fuel),
    path('approve_post/<id>/',views.approve_post),
    path('Admin_reject_fuel/',views.reject_fuel),
    path('reject_post/<id>', views.reject_post),
    path('Admin_view_EV/',views.view_EV),
    path('Admin_view_EV_post/',views.view_EV_post),
    path('Admin_approve_EV/',views.approve_EV),
    path('Admin_approve_EV_post/<id>',views.approve_EV_post),
    path('Admin_reject_EV/',views.reject_EV),
    path('Admin_reject_EV_post/<id>',views.reject_EV_post),
    path('approve_worker_post/<id>',views.approve_worker_post),
    path('reject_worker_post/<id>',views.reject_worker_post),
    path('wrkr_send_req/',views.wrkr_send_req),
    path('Admin_view_worker/',views.view_worker),
    path('Admin_approve_worker/',views.approve_worker),
    path('Admin_reject_worker/',views.reject_worker),
    path('Admin_complaint/',views.complaint),
    path('Admin_complaint_post/',views.complaint_post),
    path('Admin_reply/<id>',views.reply),
    path('Admin_reply_post/',views.reply_post),
    path('Admin_review/',views.review),
    path('review_post/',views.review_post),
    path('Fuelstation_home/',views.home_fuelstation),
    path('Fuelstation_signup_fuel/',views.signup_fuel),
    path('Fuelstation_signupfuel_post/',views.signupfuel_post),
    path('Fuelstation_passwordfuel_change/', views.passwordfuel_change),
    path('passwordfuel_post/', views.passwordfuel_post),
    path('Fuelstation_view_profile/',views.view_profile),
    path('Fuelstation_edit_profile/',views.edit_profile),
    path('edit_profile_post/',views.edit_profile_post),
    path('Fuelstation_add_staff/',views.add_staff),
    path('Fuelstation_add_staff_post/',views.addstaff_post),
    path('Fuelstation_edit_staff/<id>',views.edit_staff),
    path('Fuelstation_edit_staff_post/',views.editstaff_post),
    path('Fuelstation_view_staff/',views.view_staff),
    path('Fuelstation_view_staff_post/',views.view_staff_post),
    path('Fuelstation_add_stock/',views.add_stock),
    path('Fuelstation_add_stock_post/',views.addstock_post),
    path('Fuelstation_edit_stock/<id>',views.edit_stock),
    path('Fuelstation_edit_stock_post/',views.editstock_post),
    path('Fuelstation_view_stock/',views.view_stock),
    path('Fuelstation_view_stock_post/',views.view_stock_post),
    path('Fuelstation_delete_stock/<id>',views.delete_stock),
    path('Fuelstation_delete_staff/<id>',views.delete_staff),
    path('fuel_send_req/',views.fuel_send_req),
    path('user_view_fuel_Req_status/',views.user_view_fuel_Req_status),
    path('Fuelstation_view_request_to_staff/',views.view_request_to_staff),
    path('Fuelstation_allocation/<id>',views.allocation),
    path('Fuelstation_allocation_post/',views.allocation_post),
    path('Fuelstation_view_allocation/',views.view_allocation),
    path('Fuelstation_view_allocation_post/',views.view_allocation_post),
    path('Fuelstation_payment/', views.payment),
    path('EVstation_home/',views.home_EV),
    path('EVstation_signup_EV/', views.signup_EV),
    path('EVstation_signup_EV_post/', views.signupEV_post),
    path('EVstation_passwordEV_change/', views.passwordEV_change),
    path('passwordEV_post/', views.passwordEV_post),
    path('EVstation_edit_EV/', views.edit_EV),
    path('EVstation_edit_EV_post/',views.editEV_post),
    path('EVstation_view_profile_EV/', views.view_profile_EV),
    path('user_ev_payment/', views.user_ev_payment),
    path('EVstation_view_payment_EV/', views.view_payment_EV),
    path('EVstation_view_payment_EV_post/', views.view_payment_EV_post),
    path('EVstation_add_slot/', views.add_slot),
    path('EVstation_add_slot_post/', views.addslot_post),
    path('EVstation_edit_slot/<id>', views.edit_slot),
    path('EVstation_edit_slot_post/', views.editslot_post),
    path('EVstation_delete_slot/<id>', views.delete_slot),
    path('EVstation_view_slot/', views.view_slot),
    path('EVstation_view_slot_post/', views.view_slot_post),
    path('EVstation_view_booking/', views.view_booking),
    path('EVstation_view_booking_post/', views.view_booking_post),

    # worker

    path('flut_login_post/', views.flut_login_post),
    path('Workerstation_signup_worker/', views.signup_worker),
    path('signupwrk_post/', views.signupwrk_post),
    path('view_profile_wrkr/', views.view_profile_wrkr),
    path('editprofilewrk_post/', views.editprofilewrk_post),
    path('passwordwrkr_post/', views.passwordwrkr_post),
    path('view_service/', views.view_service),
    path('add_service/', views.add_service),
    path('addservice_post/', views.addservice_post),
    path('edit_service/', views.edit_service),
    path('editservice_post/', views.editservice_post),
    path('delete_service/', views.delete_service),
    path('worker_view_service_req/', views.worker_view_service_req),
    path('approve_service_req/', views.approve_service_req),
    path('reject_service_req/', views.reject_service_req),
    path('wrkr_view_approved_req/', views.wrkr_view_approved_req),
    path('wrkr_view_rejected_req/', views.wrkr_view_rejected_req),
    path('user_wrkr_payment/', views.user_wrkr_payment),
    path('view_payment_wrkr/', views.view_payment_wrkr),
    path('wrkr_view_review/', views.wrkr_view_review),

    # user

    path('User_signup_user_post/', views.signupusr_post),
    path('User_view_profile_usr/', views.view_profile_usr),
    # path('User_edit_profile_usr/', views.edit_profile_usr),
    path('editprofileusr_post/', views.editprofileusr_post),
    path('passwordusr_post/', views.passwordusr_post),
    #path('User_view_nearby_station/', views.view_nearby_station),
    path('User_view_slot_user/', views.view_slot_user),
    # path('view_slot_user_post/',views.view_slot_usr_post),
    path('view_stock_usr/', views.view_stock_usr),
    path('User_stock_usr/', views.stock_usr),
    path('User_view_EV/', views.view_EV_usr),
    path('User_slot_EV/', views.slot_usr),
    path('User_booking_usr/', views.booking_usr),
    path('User_view_book/', views.view_book_user),
    path('User_history_usr/', views.history_usr),
    # path('User_view_payment_usr/', views.view_payment_usr),
    path('User_view_complaint_usr/', views.user_send_complaint),
    path('User_user_view_complaint/', views.user_view_complaint),
    path('User_send_review/', views.user_send_review),
    path('User_user_view_worker/', views.user_view_worker),
    path('user_view_fuelstation/', views.user_view_fuelstation),
    path('user_view_evstation/', views.user_view_evstation),
    path('user_view_stock/', views.user_view_stock),
    path('user_send_wrokreq/', views.user_send_wrokreq),
    path('User_previous_bookings/', views.usr_view_previous_bookings),
    path('user_view_service/', views.user_view_service),
    path('user_view_Req_service/', views.user_view_Req_service),
    path('user_send_evreq/', views.user_send_evreq),
    path('User_view_Req_slot/', views.user_view_Req_slot),
    path('view_payment_wrkr_history/', views.view_payment_wrkr_history),
    path('view_payment_ev_history/', views.view_payment_ev_history),
    path('add_reminder/', views.add_reminder),
    path('user_view_reminder/', views.user_view_reminder),
    path('chat/', views.chat),
    path('petrolpriceprediction/', views.petrolpriceprediction),

]
